/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testdatabase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author iMaD
 */
public class University extends javax.swing.JFrame {

    /**
     * Creates new form University
     */
    Connection myCon = null;
    PreparedStatement ps ;
    public University() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	 // this comment by Ahmad
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        student_num_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        student_num_txt = new javax.swing.JTextField();
        first_name_txt = new javax.swing.JTextField();
        last_name_txt = new javax.swing.JTextField();
        Add_student_btn = new javax.swing.JButton();
        exit1_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        student_num_edit_txt = new javax.swing.JTextField();
        show_edit_btn = new javax.swing.JButton();
        first_name_edit_txt = new javax.swing.JTextField();
        last_name_edit_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        exit2_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        student_num_delete_txt = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        exit3_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("University with Database");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        student_num_lbl.setText("Student Number:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        student_num_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_num_txtActionPerformed(evt);
            }
        });

        Add_student_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add_student_btn.setForeground(new java.awt.Color(0, 0, 153));
        Add_student_btn.setText("Add Student");
        Add_student_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_student_btnActionPerformed(evt);
            }
        });

        exit1_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit1_btn.setForeground(new java.awt.Color(255, 0, 0));
        exit1_btn.setText("Exit");
        exit1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(student_num_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(last_name_txt)
                            .addComponent(Add_student_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(exit1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(student_num_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(student_num_txt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(Add_student_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        info.addTab("Add", jPanel1);

        jLabel1.setText("Student Number:");

        student_num_edit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_num_edit_txtActinPerformed(evt);
            }
        });

        show_edit_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        show_edit_btn.setForeground(new java.awt.Color(102, 0, 102));
        show_edit_btn.setText("Show");
        show_edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_edit_btnActionPerformed(evt);
            }
        });

        first_name_edit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_edit_txtActinPerformed(evt);
            }
        });

        last_name_edit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_edit_txtActinPerformed(evt);
            }
        });

        jLabel4.setText("First name:");

        jLabel5.setText("Last Name:");

        exit2_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit2_btn.setForeground(new java.awt.Color(255, 0, 0));
        exit2_btn.setText("Exit");
        exit2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2_btnActionPerformed(evt);
            }
        });

        update_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_btn.setForeground(new java.awt.Color(0, 153, 51));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(last_name_edit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(first_name_edit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(student_num_edit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(183, 183, 183)
                            .addComponent(show_edit_btn))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(update_btn)
                        .addContainerGap(88, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(exit2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_num_edit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(show_edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name_edit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name_edit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        info.addTab("Edit", jPanel2);

        jLabel6.setText("Student Num:");

        delete_btn.setBackground(new java.awt.Color(255, 0, 0));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        exit3_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit3_btn.setForeground(new java.awt.Color(255, 0, 0));
        exit3_btn.setText("Exit");
        exit3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit3_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(student_num_delete_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(delete_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_num_delete_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(exit3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        info.addTab("Delete", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(info)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(info)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void last_name_edit_txtActinPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_edit_txtActinPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_edit_txtActinPerformed

    private void first_name_edit_txtActinPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_edit_txtActinPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_edit_txtActinPerformed

    private void student_num_edit_txtActinPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_num_edit_txtActinPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_num_edit_txtActinPerformed

    private void Add_student_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_student_btnActionPerformed
        myCon = DBHelper.connectDB();
        String sql_insert = "INSERT INTO students (student_num,first_name,last_name)VALUES(?,?,?);";
        try {
            ps = myCon.prepareStatement(sql_insert);
            ps.setInt(1, Integer.parseInt(student_num_txt.getText().trim()));
            ps.setString(2, first_name_txt.getText().trim());
            ps.setString(3, last_name_txt.getText().trim());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "New student successfully added.");
            student_num_txt.setText("");
        } catch (SQLException ex) {
            System.out.println("error");
          //  Logger.getLogger(University.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Add_student_btnActionPerformed

    private void exit1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit1_btnActionPerformed

    private void exit2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit2_btnActionPerformed

    private void exit3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit3_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit3_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        String query = "UPDATE students set first_name=?, last_name=? where student_num=?";
        myCon = DBHelper.connectDB();
        try {
            ps = myCon.prepareStatement(query);
            ps.setInt(3, Integer.parseInt(student_num_edit_txt.getText().trim()));
            ps.setString(1,first_name_edit_txt.getText().trim());
            ps.setString(2, last_name_edit_txt.getText().trim());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student successfully updated");
        } catch (SQLException ex) {
            Logger.getLogger(University.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void show_edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_edit_btnActionPerformed
        String query = "SELECT first_name, last_name from students where student_num=?";
        myCon = DBHelper.connectDB();
        try {
            ps = myCon.prepareStatement(query);
            ps.setInt(1, Integer.parseInt(student_num_edit_txt.getText().trim()));
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                first_name_edit_txt.setText(rs.getString("first_name"));
                last_name_edit_txt.setText(rs.getString("last_name"));
                
            }
            
        } catch (SQLException ex) {
          //  Logger.getLogger(University.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("error");
        }
        
    }//GEN-LAST:event_show_edit_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        String query = "delete from students where student_num=?";
        myCon = DBHelper.connectDB();
        try {
            ps = myCon.prepareStatement(query);
            ps.setInt(1, Integer.parseInt(student_num_delete_txt.getText().trim()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Deleted");
        } catch (SQLException ex) {
            Logger.getLogger(University.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void student_num_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_num_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_num_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(University.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(University.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(University.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(University.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new University().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_student_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton exit1_btn;
    private javax.swing.JButton exit2_btn;
    private javax.swing.JButton exit3_btn;
    private javax.swing.JTextField first_name_edit_txt;
    private javax.swing.JTextField first_name_txt;
    private javax.swing.JTabbedPane info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField last_name_edit_txt;
    private javax.swing.JTextField last_name_txt;
    private javax.swing.JButton show_edit_btn;
    private javax.swing.JTextField student_num_delete_txt;
    private javax.swing.JTextField student_num_edit_txt;
    private javax.swing.JLabel student_num_lbl;
    private javax.swing.JTextField student_num_txt;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
